@apiV1 = http://localhost:4001/api/v1
@authBase = {{apiV1}}/auth

###
# Register (POST /api/v1/auth/register)
POST {{authBase}}/register
Content-Type: application/json

{
  "firstName": "test_user_01",
  "lastName": "test_user_01",
  "email": "test_user_01@example.com",
  "password": "password123"
}

