export const ERROR_CODES = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_LOCKED: "OTP_LOCKED",
  OTP_SESSION_NOT_FOUND: "OTP_SESSION_NOT_FOUND",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  REGISTRATION_SESSION_EXPIRED: "REGISTRATION_SESSION_EXPIRED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
